#!/usr/bin/env bash

# Inspired from:
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

EXCLUDE_PATTERN='-not -path "*/.git*" -not -path "*/node_modules*" -not -path "*/.cache*" -not -path "*/.nvm*" -not -path "*/.zoom"'

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$( (
    eval find ~/personal ~/ ~/.dotfiles ~/.dotfiles/.local/ -mindepth 1 -maxdepth 1 -type d $EXCLUDE_PATTERN
    eval find ~/school -type d $EXCLUDE_PATTERN
  ) | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

if [[ -n $TMUX ]]; then
  tmux switch-client -t "$selected_name"
else
  tmux attach-session -t "$selected_name"
fi
